//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BH
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTSearch.ConfigurationDLL", Namespace="http://schemas.datacontract.org/2004/07/FTSearchNet")]
    public partial struct FTSearchConfigurationDLL
    {
        
        private bool AutoSaveIndexField;
        
        private uint AutoStemmingOnField;
        
        private uint CountWordInPhraseField;
        
        private uint DocumentNameSizeField;
        
        private byte[] IndexPathField;
        
        private uint InstanceNumberField;
        
        private bool IsCreateNewInstanceOnUpdateField;
        
        private bool IsCustomPathField;
        
        private bool IsUseEnglishAlphabetField;
        
        private bool IsUseNumberAlphabetField;
        
        private bool IsUseRussianAlphabetField;
        
        private bool IsUseUkranianAlphabetField;
        
        private uint LimitTopResultsField;
        
        private ulong LimitUsedMemoryField;
        
        private uint MaxLenWordField;
        
        private uint MemoryModeField;
        
        private uint MinLenWordField;
        
        private uint RelevantLevelField;
        
        private uint WordsHeaderBaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AutoSaveIndex
        {
            get
            {
                return this.AutoSaveIndexField;
            }
            set
            {
                this.AutoSaveIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint AutoStemmingOn
        {
            get
            {
                return this.AutoStemmingOnField;
            }
            set
            {
                this.AutoStemmingOnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint CountWordInPhrase
        {
            get
            {
                return this.CountWordInPhraseField;
            }
            set
            {
                this.CountWordInPhraseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint DocumentNameSize
        {
            get
            {
                return this.DocumentNameSizeField;
            }
            set
            {
                this.DocumentNameSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] IndexPath
        {
            get
            {
                return this.IndexPathField;
            }
            set
            {
                this.IndexPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint InstanceNumber
        {
            get
            {
                return this.InstanceNumberField;
            }
            set
            {
                this.InstanceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCreateNewInstanceOnUpdate
        {
            get
            {
                return this.IsCreateNewInstanceOnUpdateField;
            }
            set
            {
                this.IsCreateNewInstanceOnUpdateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCustomPath
        {
            get
            {
                return this.IsCustomPathField;
            }
            set
            {
                this.IsCustomPathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUseEnglishAlphabet
        {
            get
            {
                return this.IsUseEnglishAlphabetField;
            }
            set
            {
                this.IsUseEnglishAlphabetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUseNumberAlphabet
        {
            get
            {
                return this.IsUseNumberAlphabetField;
            }
            set
            {
                this.IsUseNumberAlphabetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUseRussianAlphabet
        {
            get
            {
                return this.IsUseRussianAlphabetField;
            }
            set
            {
                this.IsUseRussianAlphabetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsUseUkranianAlphabet
        {
            get
            {
                return this.IsUseUkranianAlphabetField;
            }
            set
            {
                this.IsUseUkranianAlphabetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint LimitTopResults
        {
            get
            {
                return this.LimitTopResultsField;
            }
            set
            {
                this.LimitTopResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong LimitUsedMemory
        {
            get
            {
                return this.LimitUsedMemoryField;
            }
            set
            {
                this.LimitUsedMemoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MaxLenWord
        {
            get
            {
                return this.MaxLenWordField;
            }
            set
            {
                this.MaxLenWordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MemoryMode
        {
            get
            {
                return this.MemoryModeField;
            }
            set
            {
                this.MemoryModeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint MinLenWord
        {
            get
            {
                return this.MinLenWordField;
            }
            set
            {
                this.MinLenWordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint RelevantLevel
        {
            get
            {
                return this.RelevantLevelField;
            }
            set
            {
                this.RelevantLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint WordsHeaderBase
        {
            get
            {
                return this.WordsHeaderBaseField;
            }
            set
            {
                this.WordsHeaderBaseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTSearch.Result", Namespace="http://schemas.datacontract.org/2004/07/FTSearchNet")]
    public partial struct FTSearchResult
    {
        
        private string NameField;
        
        private BH.FTSearchResultPosition[] PositionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BH.FTSearchResultPosition[] Positions
        {
            get
            {
                return this.PositionsField;
            }
            set
            {
                this.PositionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTSearch.ResultPosition", Namespace="http://schemas.datacontract.org/2004/07/FTSearchNet")]
    public partial struct FTSearchResultPosition
    {
        
        private int LengthField;
        
        private int StartPositionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Length
        {
            get
            {
                return this.LengthField;
            }
            set
            {
                this.LengthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartPosition
        {
            get
            {
                return this.StartPositionField;
            }
            set
            {
                this.StartPositionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FTSearch.FTSInstanceInfo", Namespace="http://schemas.datacontract.org/2004/07/FTSearchNet")]
    public partial struct FTSearchFTSInstanceInfo
    {
        
        private uint ControlValueField;
        
        private uint CountWordsHDDField;
        
        private uint CountWordsRAMField;
        
        private uint DocumentNameSizeField;
        
        private bool HasErrorField;
        
        private string LastErrorMessageField;
        
        private uint LastNameIDHDDField;
        
        private uint LastNameIDRAMField;
        
        private uint RelevantLevelField;
        
        private uint ReservedValue1Field;
        
        private uint ReservedValue2Field;
        
        private uint ReservedValue3Field;
        
        private uint ReservedValue4Field;
        
        private uint ReservedValue5Field;
        
        private ulong TotalMemoryField;
        
        private ulong UsedMemoryField;
        
        private uint VersionField;
        
        private uint WordsHeaderBaseField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ControlValue
        {
            get
            {
                return this.ControlValueField;
            }
            set
            {
                this.ControlValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint CountWordsHDD
        {
            get
            {
                return this.CountWordsHDDField;
            }
            set
            {
                this.CountWordsHDDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint CountWordsRAM
        {
            get
            {
                return this.CountWordsRAMField;
            }
            set
            {
                this.CountWordsRAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint DocumentNameSize
        {
            get
            {
                return this.DocumentNameSizeField;
            }
            set
            {
                this.DocumentNameSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasError
        {
            get
            {
                return this.HasErrorField;
            }
            set
            {
                this.HasErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastErrorMessage
        {
            get
            {
                return this.LastErrorMessageField;
            }
            set
            {
                this.LastErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint LastNameIDHDD
        {
            get
            {
                return this.LastNameIDHDDField;
            }
            set
            {
                this.LastNameIDHDDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint LastNameIDRAM
        {
            get
            {
                return this.LastNameIDRAMField;
            }
            set
            {
                this.LastNameIDRAMField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint RelevantLevel
        {
            get
            {
                return this.RelevantLevelField;
            }
            set
            {
                this.RelevantLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservedValue1
        {
            get
            {
                return this.ReservedValue1Field;
            }
            set
            {
                this.ReservedValue1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservedValue2
        {
            get
            {
                return this.ReservedValue2Field;
            }
            set
            {
                this.ReservedValue2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservedValue3
        {
            get
            {
                return this.ReservedValue3Field;
            }
            set
            {
                this.ReservedValue3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservedValue4
        {
            get
            {
                return this.ReservedValue4Field;
            }
            set
            {
                this.ReservedValue4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint ReservedValue5
        {
            get
            {
                return this.ReservedValue5Field;
            }
            set
            {
                this.ReservedValue5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong TotalMemory
        {
            get
            {
                return this.TotalMemoryField;
            }
            set
            {
                this.TotalMemoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ulong UsedMemory
        {
            get
            {
                return this.UsedMemoryField;
            }
            set
            {
                this.UsedMemoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public uint WordsHeaderBase
        {
            get
            {
                return this.WordsHeaderBaseField;
            }
            set
            {
                this.WordsHeaderBaseField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BH.FTService")]
    public interface FTService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/IsStarted", ReplyAction="http://tempuri.org/FTService/IsStartedResponse")]
        System.Threading.Tasks.Task<bool> IsStartedAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/GetConfiguration", ReplyAction="http://tempuri.org/FTService/GetConfigurationResponse")]
        System.Threading.Tasks.Task<BH.FTSearchConfigurationDLL> GetConfigurationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/GetDefaultConfiguration", ReplyAction="http://tempuri.org/FTService/GetDefaultConfigurationResponse")]
        System.Threading.Tasks.Task<BH.FTSearchConfigurationDLL> GetDefaultConfigurationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/SetConfiguration", ReplyAction="http://tempuri.org/FTService/SetConfigurationResponse")]
        System.Threading.Tasks.Task SetConfigurationAsync(BH.FTSearchConfigurationDLL configuration);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/Start", ReplyAction="http://tempuri.org/FTService/StartResponse")]
        System.Threading.Tasks.Task StartAsync(int instanceNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/SearchPhrase", ReplyAction="http://tempuri.org/FTService/SearchPhraseResponse")]
        System.Threading.Tasks.Task<BH.FTSearchResult[]> SearchPhraseAsync(string phrase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/GetInfo", ReplyAction="http://tempuri.org/FTService/GetInfoResponse")]
        System.Threading.Tasks.Task<BH.FTSearchFTSInstanceInfo> GetInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/IndexText", ReplyAction="http://tempuri.org/FTService/IndexTextResponse")]
        System.Threading.Tasks.Task<bool> IndexTextAsync(string aliasName, string contentText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/SaveIndex", ReplyAction="http://tempuri.org/FTService/SaveIndexResponse")]
        System.Threading.Tasks.Task SaveIndexAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/MergeIndexes", ReplyAction="http://tempuri.org/FTService/MergeIndexesResponse")]
        System.Threading.Tasks.Task MergeIndexesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/Stop", ReplyAction="http://tempuri.org/FTService/StopResponse")]
        System.Threading.Tasks.Task StopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FTService/CheckIndexes", ReplyAction="http://tempuri.org/FTService/CheckIndexesResponse")]
        System.Threading.Tasks.Task CheckIndexesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface FTServiceChannel : BH.FTService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class FTServiceClient : System.ServiceModel.ClientBase<BH.FTService>, BH.FTService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FTServiceClient() : 
                base(FTServiceClient.GetDefaultBinding(), FTServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_FTService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FTServiceClient.GetBindingForEndpoint(endpointConfiguration), FTServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FTServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FTServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FTServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> IsStartedAsync()
        {
            return base.Channel.IsStartedAsync();
        }
        
        public System.Threading.Tasks.Task<BH.FTSearchConfigurationDLL> GetConfigurationAsync()
        {
            return base.Channel.GetConfigurationAsync();
        }
        
        public System.Threading.Tasks.Task<BH.FTSearchConfigurationDLL> GetDefaultConfigurationAsync()
        {
            return base.Channel.GetDefaultConfigurationAsync();
        }
        
        public System.Threading.Tasks.Task SetConfigurationAsync(BH.FTSearchConfigurationDLL configuration)
        {
            return base.Channel.SetConfigurationAsync(configuration);
        }
        
        public System.Threading.Tasks.Task StartAsync(int instanceNumber)
        {
            return base.Channel.StartAsync(instanceNumber);
        }
        
        public System.Threading.Tasks.Task<BH.FTSearchResult[]> SearchPhraseAsync(string phrase)
        {
            return base.Channel.SearchPhraseAsync(phrase);
        }
        
        public System.Threading.Tasks.Task<BH.FTSearchFTSInstanceInfo> GetInfoAsync()
        {
            return base.Channel.GetInfoAsync();
        }
        
        public System.Threading.Tasks.Task<bool> IndexTextAsync(string aliasName, string contentText)
        {
            return base.Channel.IndexTextAsync(aliasName, contentText);
        }
        
        public System.Threading.Tasks.Task SaveIndexAsync()
        {
            return base.Channel.SaveIndexAsync();
        }
        
        public System.Threading.Tasks.Task MergeIndexesAsync()
        {
            return base.Channel.MergeIndexesAsync();
        }
        
        public System.Threading.Tasks.Task StopAsync()
        {
            return base.Channel.StopAsync();
        }
        
        public System.Threading.Tasks.Task CheckIndexesAsync()
        {
            return base.Channel.CheckIndexesAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_FTService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_FTService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FTServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_FTService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FTServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_FTService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_FTService,
        }
    }
}
