/*
# Copyright(C) 2010-2020 Viacheslav Makoveichuk (email: slv709@gmail.com, skype: vyacheslavm81)
# This file is part of Black Hole FTS.
#
# Black Hole FTS is free software : you can redistribute it and / or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Black Hole FTS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Foobar.  If not, see <http://www.gnu.org/licenses/>.
*/

using BH.WCF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BH.BoobenRobot
{
    public class KhafSite : Site
    {
        public KhafSite(FTService service) : base(service)
        {
            BaseUrl = "kharkovforum.com";
            Code = "khaf";
            SiteEncoding = Encoding.GetEncoding("windows-1251");
            PageDelay = TimeSpan.FromSeconds(1);
            SiteDelay = TimeSpan.FromHours(4);
            ErrorDelay = TimeSpan.FromMinutes(15);
        }

        protected override List<Page> GetDashboards()
        {
            //return GetDashboards("https://www.kharkovforum.com", "(?<num>[0-9]+)https://www.kharkovforum.com/forumdisplay.php?f=[0-9]+");

            return new List<Page>
            {
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=3"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=35"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=147"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=435"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=138"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=73"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=1"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=159"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=509"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=30"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=173"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=106"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=430"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=493"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=129"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=28"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=125"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=126"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=134"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=257"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=131"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=301"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=262"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=167"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=258"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=252"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=137"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=48"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=244"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=217"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=46"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=332"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=107"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=451"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=122"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=123"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=151"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=297"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=40"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=509"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=409"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=164"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=410"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=83"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=266"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=184"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=200"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=267"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=189"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=253"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=193"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=411"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=187"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=357"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=506"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=360"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=319"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=413"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=507"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=277"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=109"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=447"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=162"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=344"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=342"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=345"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=337"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=338"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=160"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=161"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=440"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=341"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=163"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=450"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=343"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=336"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=339"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=180"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=92"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=185"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=368"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=152"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=236"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=306"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=361"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=409"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=37"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=433"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=415"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=61"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=279"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=75"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=270"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=269"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=36"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=130"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=421"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=420"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=304"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=418"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=417"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=419"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=136"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=481"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=181"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=132"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=166"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=478"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=44"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=119"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=466"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=124"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=179"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=41"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=479"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=139"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=84"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=484"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=482"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=483"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=485"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=365"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=101"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=375"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=517"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=515"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=478"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=292"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=432"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=518"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=516"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=117"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=512"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=368"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=254"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=487"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=219"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=495"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=386"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=273"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=408"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=272"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=361"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=275"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=396"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=274"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=158"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=407"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=263"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=330"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=406"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=378"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=234"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=136"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=235"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=271"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=270"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=300"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=158"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=226"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=196"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=100"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=437"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=436"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=439"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=440"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=438"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=442"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=215"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=392"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=356"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=391"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=393"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=388"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=397"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=398"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=389"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=390"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=242"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=387"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=286"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=355"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=188"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=354"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=212"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=291"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=400"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=96"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=405"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=392"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=285"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=401"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=398"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=277"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=404"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=335"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=369"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=153"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=380"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=382"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=379"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=372"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=335"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=97"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=384"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=381"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=373"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=383"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=377"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=219"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=78"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=358"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=98"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=476"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=449"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=412"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=477"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=474"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=473"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=475"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=221"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=425"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=337"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=426"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=448"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=120"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=359"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=208"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=239"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=360"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=113"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=209"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=165"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=216"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=451"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=241"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=446"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=80"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=115"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=445"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=195"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=191"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=313"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=424"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=80"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=307"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=42"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=99"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=201"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=51"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=423"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=422"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=43"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=104"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=145"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=144"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=428"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=146"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=445"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=142"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=60"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=143"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=186"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=207"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=280"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=264"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=338"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=218"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=40"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=116"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=112"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=233"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=102"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=363"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=114"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=115"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=488"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=204"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=395"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=249"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=489"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=202"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=247"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=108"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=294"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=206"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=427"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=248"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=203"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=287"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=281"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=205"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=349"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=347"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=346"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=177"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=353"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=352"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=350"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=250"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=195"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=284"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=315"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=519"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=214"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=38"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=364"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=232"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=86"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=190"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=168"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=134"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=57"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=502"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=312"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=414"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=245"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=125"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=314"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=148"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=139"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=127"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=149"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=141"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=290"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=92"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=153"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=264"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=150"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=416"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=307"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=140"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=164"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=252"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=151"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=152"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=306"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=424"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=318"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=39"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=302"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=339"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=52"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=81"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=135"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=307"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=5"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=234"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=53"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=246"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=497"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=256"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=54"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=80"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=444"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=293"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=80"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=307"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=223"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=181"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=136"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=45"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=27"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=240"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=478"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=8"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=211"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=20"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=87"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=12"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=137"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=86"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=129"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=174"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=198"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=170"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=84"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=126"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=502"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=28"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=245"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=64"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=67"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=120"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=199"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=78"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=196"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=226"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=68"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=394"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=71"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=167"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=202"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=105"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=111"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=234"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=171"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=6"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=252"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=94"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=220"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=221"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=10"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=74"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=195"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=33"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=128"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=190"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=95"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=190"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=77"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=178"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=150"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=310"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=475"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=364"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=34"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=510"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=9"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=511"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=229"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=72"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=298"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=231"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=288"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=230"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=364"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=58"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=157"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=191"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=14"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=243"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=19"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=443"},
                new Page() {URL = "https://www.kharkovforum.com/forumdisplay.php?f=66"},
            };
        }

        protected override List<string> GetDocNumberByUrl(string url)
        {
            return this.ExtractByRegexp(url, "t=(?<num>[0-9]+)");
        }

        protected override string GetUrlByDocNumber(string docNumber, int page, string dashboard)
        {
            return string.Format("https://www.kharkovforum.com/showthread.php?t={0}&page={1}", docNumber, page);
        }

        protected override List<Page> OnDashboardLoaded(Page page)
        {
            List<Page> pages = new List<Page>();

            List<string> nums = ExtractByRegexp(page.HtmlContent, "thread_title_(?<num>[0-9]+)");

            List<string> labels = GetParts(page.HtmlContent, "<td class=\"alt1\" align=\"center\">", "</td>");

            if (nums.Count == labels.Count)
            {
                for (int i = nums.Count - 1; i >= 0; i--)
                {
                    string url = GetUrlByDocNumber(nums[i], 1, null);
                    CheckLabelAndAddPage(pages, url, labels[i]);
                }
            }

            return pages;
        }

        protected override void OnPageLoaded(Page page)
        {
            //content
            page.FileContent = (" " + GetMessages("<div id=\"post_message_", "</div>", "div", page.HtmlContent));

            //check load next page
            page.NeedLoadNextPage = (page.HtmlContent.IndexOf("Конец <strong>&raquo;</strong>") >= 0) ||
                                    (page.HtmlContent.IndexOf(">&gt;</a>") >= 0);
        }
    }
}

